openapi: 3.0.3

info:
  title: API сервиса сотрудников - материалы
  description: Справочник материалов сервиса
  version: 0.0.1

tags:
  - name: Materials
    description: Материалы

paths:
  /materials:
    get:
      operationId: getAllMaterials
      summary: Получить список всех материалов
      description: Получить список всех материалов
      tags:
        - Materials
      parameters:
        - $ref: '../objects.yaml#/components/parameters/pageNumber'
        - $ref: '../objects.yaml#/components/parameters/pageSize'
        - $ref: '../objects.yaml#/components/parameters/sortingType'
        - $ref: '../objects.yaml#/components/parameters/sortingFieldName'
        - $ref: '../objects.yaml#/components/parameters/searchingFilter'
      responses:
        200:
          description: Данные были успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaterialInfoPagingResponse'
        400:
          $ref: '../service.yaml#/components/responses/BAD_REQUEST'
        401:
          $ref: '../service.yaml#/components/responses/UNAUTHORIZED'
        403:
          $ref: '../service.yaml#/components/responses/FORBIDDEN'
        404:
          $ref: '../service.yaml#/components/responses/NOT_FOUND'
        500:
          $ref: '../service.yaml#/components/responses/INTERNAL_SERVER_ERROR'
    post:
      operationId: createMaterial
      summary: Сохранить новый материал
      description: Сохранить новый материал
      tags:
        - Materials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaterialSaveRequest'
      responses:
        200:
          description: Данные были успешно сохранены
        400:
          $ref: '../service.yaml#/components/responses/BAD_REQUEST'
        401:
          $ref: '../service.yaml#/components/responses/UNAUTHORIZED'
        403:
          $ref: '../service.yaml#/components/responses/FORBIDDEN'
        404:
          $ref: '../service.yaml#/components/responses/NOT_FOUND'
        500:
          $ref: '../service.yaml#/components/responses/INTERNAL_SERVER_ERROR'

  /materials/{materialId}:
    get:
      operationId: getMaterialById
      summary: Получить данные материала по идентификатору
      description: Получить основные данные материала
      parameters:
        - $ref: '../objects.yaml#/components/parameters/materialId'
      tags:
        - Materials
      responses:
        200:
          description: Данные были успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaterialInfoResponse'
        400:
          $ref: '../service.yaml#/components/responses/BAD_REQUEST'
        401:
          $ref: '../service.yaml#/components/responses/UNAUTHORIZED'
        403:
          $ref: '../service.yaml#/components/responses/FORBIDDEN'
        404:
          $ref: '../service.yaml#/components/responses/NOT_FOUND'
        500:
          $ref: '../service.yaml#/components/responses/INTERNAL_SERVER_ERROR'
    put:
      operationId: updateMaterial
      summary: Изменить материал по идентификатору
      description: Изменить данные материала
      parameters:
        - $ref: '../objects.yaml#/components/parameters/materialId'
      tags:
        - Materials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaterialSaveRequest'
      responses:
        200:
          description: Данные были успешно обновлены
        400:
          $ref: '../service.yaml#/components/responses/BAD_REQUEST'
        401:
          $ref: '../service.yaml#/components/responses/UNAUTHORIZED'
        403:
          $ref: '../service.yaml#/components/responses/FORBIDDEN'
        404:
          $ref: '../service.yaml#/components/responses/NOT_FOUND'
        500:
          $ref: '../service.yaml#/components/responses/INTERNAL_SERVER_ERROR'
    delete:
      operationId: deleteMaterialById
      summary: Навсегда удалить запись материала
      description: Удалить материал
      parameters:
        - $ref: '../objects.yaml#/components/parameters/materialId'
      tags:
        - Materials
      responses:
        200:
          description: Информация успешно удалена
        400:
          $ref: '../service.yaml#/components/responses/BAD_REQUEST'
        401:
          $ref: '../service.yaml#/components/responses/UNAUTHORIZED'
        403:
          $ref: '../service.yaml#/components/responses/FORBIDDEN'
        404:
          $ref: '../service.yaml#/components/responses/NOT_FOUND'
        500:
          $ref: '../service.yaml#/components/responses/INTERNAL_SERVER_ERROR'


components:
  schemas:
    #    Модели материалов
    MaterialInfoPagingResponse:
      type: object
      properties:
        paging:
          $ref: '../service.yaml#/components/schemas/Paging'
        content:
          type: array
          items:
            $ref: '#/components/schemas/MaterialListInfoResponse'

    MaterialListInfoResponse:
      type: object
      description: Данные материала в списке материалов
      properties:
        id:
          $ref: '../objects.yaml#/components/schemas/MaterialId'
        name:
          $ref: '../objects.yaml#/components/schemas/MaterialName'
        type:
          $ref: '../objects.yaml#/components/schemas/MaterialType'
        short_info:
          $ref: '../objects.yaml#/components/schemas/MaterialShortInfo'

    MaterialSaveRequest:
      type: object
      description: Создание нового материала
      properties:
        name:
          $ref: '../objects.yaml#/components/schemas/MaterialName'
        description:
          $ref: '../objects.yaml#/components/schemas/MaterialDescription'
        type:
          $ref: '../objects.yaml#/components/schemas/MaterialType'
        length:
          $ref: '../objects.yaml#/components/schemas/MaterialLength'
        width:
          $ref: '../objects.yaml#/components/schemas/MaterialWidth'
        height:
          $ref: '../objects.yaml#/components/schemas/MaterialHeight'

    MaterialInfoResponse:
      type: object
      description: Данные материала
      properties:
        id:
          $ref: '../objects.yaml#/components/schemas/MaterialId'
        name:
          $ref: '../objects.yaml#/components/schemas/MaterialName'
        description:
          $ref: '../objects.yaml#/components/schemas/MaterialDescription'
        type:
          $ref: '../objects.yaml#/components/schemas/MaterialType'
        length:
          $ref: '../objects.yaml#/components/schemas/MaterialLength'
        width:
          $ref: '../objects.yaml#/components/schemas/MaterialWidth'
        height:
          $ref: '../objects.yaml#/components/schemas/MaterialHeight'
        available:
          $ref: '../objects.yaml#/components/schemas/MaterialAllStoragesQuantity'