spring:
  application:
    name: staff

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

app:
  cache:
    ttl:
      staff-period: '* 0 1 * * *'
      storages-period: '* 30 1 * * *'
      products-period: '* 0 2 * * *'
      materials-period: '* 30 2 * * *'
      orders-period: '* 0 3 * * *'

logging:
  level:
    ru.egartech.staff: INFO