spring:
  application:
    name: staff

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL::jdbc:postgresql://localhost:5430/postgres_db}
    username: ${DB_USERNAME::postgres_user}
    password: ${DB_PASSWORD::postgres_password}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml