spring:
  application:
    name: staff

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml